services:
    cms.action_listener:
        class: Lincode\Fly\Bundle\EventListener\BeforeControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@cms.permissions.service"]

    cms.permissions.service:
            class: Lincode\Fly\Bundle\Service\PermissionService
            arguments: ["%fly%"]

    cms.login.service:
        class: Lincode\Fly\Bundle\Service\LoginService
        arguments: ["@security.authentication_utils", "@form.factory", "@router"]
        scope: request

    fly.navegation.service:
        class: Lincode\Fly\Bundle\Service\NavegationService
        arguments: ["%fly%"]

    fly.controller.service:
        class: Lincode\Fly\Bundle\Service\FlyControllerService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    fly.form.service:
        class: Lincode\Fly\Bundle\Service\EntityFormService
        arguments: ["@doctrine.orm.entity_manager"]

    fly.upload.service:
        class: Lincode\Fly\Bundle\Service\UploadService
        arguments: ["@doctrine.orm.entity_manager", "%fly%"]