services:
    cms.action_listener:
        class: Lincode\Fly\Bundle\EventListener\BeforeControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ["@cms.permissions.service"]

    cms.permissions.service:
            class: Lincode\Fly\Bundle\Service\PermissionService
            arguments: ["%fly%"]

    cms.login.service:
        class: Lincode\Fly\Bundle\Service\LoginService
        arguments: ["@security.authentication_utils", "@form.factory", "@router"]
        scope: request

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    fly.navegation.service:
        class: Lincode\Fly\Bundle\Service\NavegationService
        arguments: ["%fly%"]

    fly.controller.service:
        class: Lincode\Fly\Bundle\Service\FlyControllerService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    fly.form.service:
        class: Lincode\Fly\Bundle\Service\EntityFormService
        arguments: ["@doctrine.orm.entity_manager"]

    fly.upload.service:
        class: Lincode\Fly\Bundle\Service\UploadService
        arguments: ["@doctrine.orm.entity_manager", "%fly%"]

    fly.twig_extension:
        class: Lincode\Fly\Bundle\Twig\FlyExtension
        arguments:
            container: "@service_container"
        public: true
        tags:
            - { name: twig.extension }